- name: Installing jdk
  apt: name=openjdk-8-jdk

- name: Java | Define variable environment
  blockinfile:
        path: ~/.bashrc
        block: |
               export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
               export PATH=$PATH:$JAVA_HOME/bin
